services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d pgdb -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    depends_on:
      - postgres
    build:
      context: .
      target: bot-image
      dockerfile: Dockerfile
    container_name: aibot
    volumes:
      - ./src/:/src/
      - ./config/:/config/
    env_file:
      - .env

  alembic:
    depends_on:
      - postgres
    build:
      context: .
      target: alembic-image
      dockerfile: Dockerfile
    volumes:
      - ./src/:/src/
      - ./config/:/config/
      - ./alembic:/alembic/
    command: uv run alembic upgrade head

volumes:
  pgdata:
    driver: local
