services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  alembic:
    depends_on:
      - postgres
    build:
      context: .
      target: alembic-image
      dockerfile: Dockerfile
    volumes:
      - ./src/:/src/
      - ./config/:/config/
      - ./alembic:/alembic/
    env_file:
      - .env
    #command: uv run alembic upgrade head


  bot:
    depends_on:
      - postgres
      - alembic
    build:
      context: .
      target: bot-image
      dockerfile: Dockerfile
    container_name: aibot
    volumes:
      - ./src/:/src/
      - ./config/:/config/
    env_file:
      - .env


volumes:
  pgdata:
    driver: local
