services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aibot
    volumes:
      - ./src/:/src/
      - ./config/:/config/
    networks:
      - backend

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d pgdb -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
volumes:
  pgdata:
networks:
  backend:
    driver: bridge