[bot]
is_debug = false
[ai]

    [ai.gemini]
        model = 'gemini-2.0-flash'

        [ai.gemini.basic]
        promt_file = './config/ai_promt.txt'
        tokens = 600
        temperature = 1.5

        [ai.gemini.full]
        promt_file = './config/ai_promt.txt'
        tokens = 600
        temperature = 0.1
