[bot]
is_debug = false
[ai]

    [ai.gemini]
        model = 'gemini-2.0-flash'
        chat_timeout = 300
        format_string = 'You have got message from {username!r}. They writing {text!r}. ADDITIONAL CONTEXT = {context!r}'
        
        [ai.gemini.basic]
        promt_file = './config/ai_promt.txt'
        tokens = 600
        temperature = 1.5

        [ai.gemini.full]
        promt_file = './config/ai_promt.txt'
        tokens = 600
        temperature = 0.2
[postgres]
dbname = 'pgdb'
username = 'admin'
password='123456'